<?php
namespace NYforms;
defined( 'ABSPATH' ) || exit;
class Privacy {
	public function hooks() { add_action( 'admin_init', array( $this, 'policy' ) ); add_filter( 'wp_privacy_personal_data_exporters', array( $this, 'exporters' ) ); add_filter( 'wp_privacy_personal_data_erasers', array( $this, 'erasers' ) ); }
	public function policy() { if ( function_exists( 'wp_add_privacy_policy_content' ) ) { wp_add_privacy_policy_content( __( 'NYforms', 'nyforms' ), wp_kses_post( __( '<p>NYforms stores submitted form values, submission time, and the referring page. It stores upload records for files explicitly requested by a form. Administrators can configure retention and use WordPress personal-data tools to export or erase entries matched by email.</p>', 'nyforms' ) ) ); } }
	public function exporters( $exporters ) { $exporters['nyforms'] = array( 'exporter_friendly_name' => __( 'NYforms submissions', 'nyforms' ), 'callback' => array( $this, 'exporter' ) ); return $exporters; }
	public function erasers( $erasers ) { $erasers['nyforms'] = array( 'eraser_friendly_name' => __( 'NYforms submissions', 'nyforms' ), 'callback' => array( $this, 'eraser' ) ); return $erasers; }
	public function exporter( $email, $page = 1 ) { global $wpdb; $limit = 100; $offset = ( $page - 1 ) * $limit; $rows = $wpdb->get_results( $wpdb->prepare( 'SELECT e.id,e.form_id,e.submitted_at,v.field_key,v.value FROM ' . $wpdb->prefix . 'nyforms_entries e INNER JOIN ' . $wpdb->prefix . 'nyforms_entry_values v ON e.id=v.entry_id WHERE v.value LIKE %s LIMIT %d OFFSET %d', '%' . $wpdb->esc_like( $email ) . '%', $limit, $offset ), ARRAY_A ); $data = array(); foreach ( $rows as $row ) { $data[] = array( 'group_id' => 'nyforms-entries', 'group_label' => __( 'NYforms submissions', 'nyforms' ), 'item_id' => 'nyforms-entry-' . $row['id'], 'data' => array( array( 'name' => __( 'Entry ID', 'nyforms' ), 'value' => $row['id'] ), array( 'name' => __( 'Submitted', 'nyforms' ), 'value' => $row['submitted_at'] ), array( 'name' => $row['field_key'], 'value' => maybe_unserialize( $row['value'] ) ) ) ); } return array( 'data' => $data, 'done' => count( $rows ) < $limit ); }
	public function eraser( $email, $page = 1 ) { global $wpdb; $ids = $wpdb->get_col( $wpdb->prepare( 'SELECT DISTINCT entry_id FROM ' . $wpdb->prefix . 'nyforms_entry_values WHERE value LIKE %s LIMIT 100', '%' . $wpdb->esc_like( $email ) . '%' ) ); foreach ( $ids as $id ) { $wpdb->update( $wpdb->prefix . 'nyforms_entries', array( 'status' => 'trashed', 'updated_at' => current_time( 'mysql', true ) ), array( 'id' => $id ), array( '%s','%s' ), array( '%d' ) ); } return array( 'items_removed' => ! empty( $ids ), 'items_retained' => false, 'messages' => array(), 'done' => count( $ids ) < 100 ); }
}
