<?php
namespace NYforms;
defined( 'ABSPATH' ) || exit;
class Repository {
	public function forms_table() { global $wpdb; return $wpdb->prefix . 'nyforms_forms'; }
	public function entries_table() { global $wpdb; return $wpdb->prefix . 'nyforms_entries'; }
	public function create_form( $data ) { global $wpdb; $form = Schema::sanitize_form( $data ); if ( is_wp_error( $form ) ) { return $form; } $now = current_time( 'mysql', true ); $wpdb->insert( $this->forms_table(), array( 'title' => $form['title'], 'status' => 'active', 'definition' => wp_json_encode( $form ), 'revision' => 1, 'created_by' => get_current_user_id(), 'created_at' => $now, 'updated_at' => $now ), array( '%s','%s','%s','%d','%d','%s','%s' ) ); return (int) $wpdb->insert_id; }
	public function update_form( $id, $data ) { global $wpdb; $existing = $this->form( $id ); if ( ! $existing ) { return new \WP_Error( 'nyforms_not_found', __( 'Form not found.', 'nyforms' ) ); } $form = Schema::sanitize_form( $data ); if ( is_wp_error( $form ) ) { return $form; } $revision = $existing['revision'] + 1; $wpdb->update( $this->forms_table(), array( 'title' => $form['title'], 'definition' => wp_json_encode( $form ), 'revision' => $revision, 'updated_at' => current_time( 'mysql', true ) ), array( 'id' => absint( $id ) ), array( '%s','%s','%d','%s' ), array( '%d' ) ); return $this->form( $id ); }
	public function form( $id ) { global $wpdb; $row = $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . $this->forms_table() . ' WHERE id = %d', $id ), ARRAY_A ); if ( $row ) { $row['definition'] = json_decode( $row['definition'], true ); } return $row; }
	public function forms( $search = '' ) { global $wpdb; $sql = 'SELECT f.*, COUNT(e.id) AS entries, SUM(CASE WHEN e.is_read = 0 AND e.status = "active" THEN 1 ELSE 0 END) AS unread FROM ' . $this->forms_table() . ' f LEFT JOIN ' . $this->entries_table() . ' e ON f.id = e.form_id'; if ( $search ) { $sql .= $wpdb->prepare( ' WHERE f.title LIKE %s', '%' . $wpdb->esc_like( $search ) . '%' ); } $sql .= ' GROUP BY f.id ORDER BY f.updated_at DESC'; return $wpdb->get_results( $sql, ARRAY_A ); }
	public function duplicate( $id ) { $form = $this->form( $id ); if ( ! $form ) { return new \WP_Error( 'nyforms_not_found' ); } $data = $form['definition']; $data['title'] = sprintf( __( '%s copy', 'nyforms' ), $form['title'] ); return $this->create_form( $data ); }
	public function set_form_status( $id, $status ) { global $wpdb; if ( ! in_array( $status, array( 'active','inactive','trash' ), true ) ) { return false; } return false !== $wpdb->update( $this->forms_table(), array( 'status' => $status, 'updated_at' => current_time( 'mysql', true ) ), array( 'id' => absint( $id ) ), array( '%s','%s' ), array( '%d' ) ); }
	public function delete_form( $id ) { global $wpdb; return false !== $wpdb->delete( $this->forms_table(), array( 'id' => absint( $id ) ), array( '%d' ) ); }
	public function create_entry( $form, $values, $hash ) { global $wpdb; $now = current_time( 'mysql', true ); $wpdb->insert( $this->entries_table(), array( 'form_id' => $form['id'], 'form_revision' => $form['revision'], 'submitted_by' => get_current_user_id(), 'source_url' => esc_url_raw( wp_get_referer() ?: '' ), 'request_hash' => $hash, 'submitted_at' => $now, 'updated_at' => $now ), array( '%d','%d','%d','%s','%s','%s','%s' ) ); $id = (int) $wpdb->insert_id; $table = $wpdb->prefix . 'nyforms_entry_values'; foreach ( $values as $key => $value ) { $wpdb->insert( $table, array( 'entry_id' => $id, 'field_key' => $key, 'value' => maybe_serialize( $value ) ), array( '%d','%s','%s' ) ); } return $id; }
	public function attach_file( $entry_id, $field_key, $attachment_id, $original_name, $mime_type ) { global $wpdb; return $wpdb->insert( $wpdb->prefix . 'nyforms_entry_files', array( 'entry_id' => $entry_id, 'field_key' => $field_key, 'attachment_id' => $attachment_id, 'original_name' => $original_name, 'mime_type' => $mime_type ), array( '%d','%s','%d','%s','%s' ) ); }
	public function entries( $form_id, $status = 'active', $search = '', $limit = 50, $offset = 0 ) { global $wpdb; $sql = 'SELECT * FROM ' . $this->entries_table() . ' WHERE form_id = %d AND status = %s'; $args = array( absint( $form_id ), $status ); if ( $search ) { $sql .= ' AND id IN (SELECT entry_id FROM ' . $wpdb->prefix . 'nyforms_entry_values WHERE value LIKE %s)'; $args[] = '%' . $wpdb->esc_like( $search ) . '%'; } $sql .= ' ORDER BY submitted_at DESC LIMIT %d OFFSET %d'; $args[] = absint( $limit ); $args[] = absint( $offset ); return $wpdb->get_results( $wpdb->prepare( $sql, $args ), ARRAY_A ); }
	public function update_entry_status( $id, $status, $read = null ) { global $wpdb; $data = array( 'status' => $status, 'updated_at' => current_time( 'mysql', true ) ); $formats = array( '%s','%s' ); if ( null !== $read ) { $data['is_read'] = (int) $read; $formats[] = '%d'; } return false !== $wpdb->update( $this->entries_table(), $data, array( 'id' => absint( $id ) ), $formats, array( '%d' ) ); }
	public function delete_entry( $id ) { global $wpdb; $id = absint( $id ); $wpdb->delete( $wpdb->prefix . 'nyforms_entry_values', array( 'entry_id' => $id ), array( '%d' ) ); $wpdb->delete( $wpdb->prefix . 'nyforms_entry_files', array( 'entry_id' => $id ), array( '%d' ) ); return false !== $wpdb->delete( $this->entries_table(), array( 'id' => $id ), array( '%d' ) ); }
	public function files_for_entry( $entry_id ) { global $wpdb; return $wpdb->get_results( $wpdb->prepare( 'SELECT * FROM ' . $wpdb->prefix . 'nyforms_entry_files WHERE entry_id = %d', $entry_id ), ARRAY_A ); }
	public function file( $id ) { global $wpdb; return $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . $wpdb->prefix . 'nyforms_entry_files WHERE id = %d', $id ), ARRAY_A ); }
	public function entry( $id ) { global $wpdb; $entry = $wpdb->get_row( $wpdb->prepare( 'SELECT * FROM ' . $this->entries_table() . ' WHERE id = %d', $id ), ARRAY_A ); if ( ! $entry ) { return null; } $rows = $wpdb->get_results( $wpdb->prepare( 'SELECT field_key,value FROM ' . $wpdb->prefix . 'nyforms_entry_values WHERE entry_id = %d', $id ), ARRAY_A ); $entry['values'] = array(); foreach ( $rows as $row ) { $entry['values'][ $row['field_key'] ] = maybe_unserialize( $row['value'] ); } return $entry; }
}
