<?php
namespace NYforms;
defined( 'ABSPATH' ) || exit;
class Notifications {
	public function send( $form, $values, $entry_id ) { foreach ( $form['definition']['notifications'] as $notification ) { if ( ! Conditions::matches( $notification['conditions'], $values ) ) { continue; } $to = $this->tokens( $notification['to'], $form, $values, $entry_id ); $recipients = array_filter( array_map( 'trim', explode( ',', $to ) ), 'is_email' ); if ( ! $recipients ) { $this->event( $form['id'], $entry_id, 'notification_invalid_recipient' ); continue; } $subject = wp_strip_all_tags( $this->tokens( $notification['subject'], $form, $values, $entry_id ) ); $message = $this->tokens( $notification['message'], $form, $values, $entry_id ); $headers = array( 'Content-Type: text/html; charset=UTF-8' ); if ( $notification['from_email'] && is_email( $notification['from_email'] ) ) { $headers[] = 'From: ' . $notification['from_name'] . ' <' . $notification['from_email'] . '>'; } $reply = $this->tokens( $notification['reply_to'], $form, $values, $entry_id ); if ( is_email( $reply ) ) { $headers[] = 'Reply-To: ' . $reply; } if ( ! wp_mail( $recipients, $subject, wp_kses_post( $message ), $headers ) ) { $this->event( $form['id'], $entry_id, 'notification_failed' ); } }
	}
	public function tokens( $text, $form, $values, $entry_id ) { return preg_replace_callback( '/\\[\\[nyforms:(field|form|site|entry):([a-zA-Z0-9_-]+)\\]\\]/', function( $match ) use ( $form, $values, $entry_id ) { if ( 'field' === $match[1] ) { return esc_html( is_array( $values[ $match[2] ] ?? '' ) ? implode( ', ', $values[ $match[2] ] ) : ( $values[ $match[2] ] ?? '' ) ); } if ( 'form' === $match[1] && 'title' === $match[2] ) { return esc_html( $form['title'] ); } if ( 'site' === $match[1] && 'name' === $match[2] ) { return esc_html( get_bloginfo( 'name' ) ); } if ( 'entry' === $match[1] && 'id' === $match[2] ) { return (string) $entry_id; } return ''; }, (string) $text ); }
	private function event( $form_id, $entry_id, $type ) { global $wpdb; $wpdb->insert( $wpdb->prefix . 'nyforms_events', array( 'form_id' => $form_id, 'entry_id' => $entry_id, 'event_type' => $type, 'context' => '{}', 'created_at' => current_time( 'mysql', true ) ), array( '%d','%d','%s','%s','%s' ) ); }
}
