<?php
namespace NYforms;
defined( 'ABSPATH' ) || exit;
class Submissions {
	public function handle() {
		if ( empty( $_POST['nyforms_action'] ) || ! in_array( $_POST['nyforms_action'], array( 'submit', 'save' ), true ) ) { return; }
		$form_id = absint( $_POST['nyforms_form_id'] ?? 0 ); $form = Plugin::instance()->repository->form( $form_id );
		if ( ! $form || ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['nyforms_token'] ?? '' ) ), 'nyforms_submit_' . $form_id ) ) { $this->fail( $form_id, array( 'form' => __( 'Your form session has expired. Please try again.', 'nyforms' ) ) ); }
		if ( 'save' === $_POST['nyforms_action'] ) { $this->save_resume( $form ); }
		if ( ! empty( $_POST['nyforms_website'] ) || ! $this->rate_allowed() || ! $this->recaptcha_valid() ) { $this->fail( $form_id, array( 'form' => __( 'We could not process this submission.', 'nyforms' ) ) ); }
		$raw = wp_unslash( $_POST['nyforms_values'] ?? array() ); $values = array(); $errors = array();
		foreach ( $form['definition']['fields'] as $field ) { if ( in_array( $field['type'], array( 'html','section','page','file','total','calculation' ), true ) || ! Conditions::matches( $field['visibility'], $raw ) ) { continue; } $value = $raw[ $field['key'] ] ?? ''; $valid = Fields::validate( $field, $value ); if ( is_wp_error( $valid ) ) { $errors[ $field['key'] ] = $valid->get_error_message(); } else { $values[ $field['key'] ] = $valid; } }
		foreach ( $form['definition']['fields'] as $field ) { if ( 'file' !== $field['type'] ) { continue; } if ( empty( $_FILES['nyforms_files']['name'][ $field['key'] ] ) ) { if ( $field['required'] ) { $errors[ $field['key'] ] = sprintf( __( '%s is required.', 'nyforms' ), $field['label'] ); } continue; } $file = array( 'name' => $_FILES['nyforms_files']['name'][ $field['key'] ], 'type' => $_FILES['nyforms_files']['type'][ $field['key'] ], 'tmp_name' => $_FILES['nyforms_files']['tmp_name'][ $field['key'] ], 'error' => $_FILES['nyforms_files']['error'][ $field['key'] ], 'size' => $_FILES['nyforms_files']['size'][ $field['key'] ] ); if ( UPLOAD_ERR_OK !== $file['error'] || $file['size'] > $field['max_size'] ) { $errors[ $field['key'] ] = __( 'The uploaded file is too large or failed to upload.', 'nyforms' ); continue; } $allowed = array_filter( array_map( 'trim', explode( ',', $field['allowed_types'] ) ) ); $check = wp_check_filetype_and_ext( $file['tmp_name'], $file['name'] ); if ( empty( $check['type'] ) || ( $allowed && ! in_array( $check['ext'], $allowed, true ) ) ) { $errors[ $field['key'] ] = __( 'This file type is not allowed.', 'nyforms' ); continue; } $values[ $field['key'] ] = array( '_upload' => $file, '_mime' => $check['type'] ); }
		foreach ( Extensions::spam_providers() as $provider ) { if ( $provider instanceof Anti_Spam_Provider && ! $provider->evaluate( $form, $values ) ) { $this->fail( $form_id, array( 'form' => __( 'We could not process this submission.', 'nyforms' ) ) ); } }
		if ( $errors ) { $this->fail( $form_id, array( 'fields' => $errors ) ); }
		$uploads = array(); foreach ( $values as $key => $value ) { if ( is_array( $value ) && isset( $value['_upload'] ) ) { $uploads[ $key ] = $value; $values[ $key ] = $value['_upload']['name']; } } $hash = hash_hmac( 'sha256', $form_id . '|' . wp_json_encode( $values ), wp_salt( 'nonce' ) ); $entry_id = Plugin::instance()->repository->create_entry( $form, $values, $hash ); foreach ( $uploads as $key => $upload ) { $this->store_file( $entry_id, $key, $upload ); } do_action( 'nyforms_entry_created', $entry_id, $form, $values ); Plugin::instance()->notifications->send( $form, $values, $entry_id );
		$confirmation = $this->confirmation( $form['definition']['confirmations'], $values ); if ( 'url' === $confirmation['type'] && 0 === strpos( $confirmation['value'], 'https://' ) ) { wp_safe_redirect( $confirmation['value'] ); exit; } if ( 'page' === $confirmation['type'] ) { $url = get_permalink( absint( $confirmation['value'] ) ); if ( $url ) { wp_safe_redirect( $url ); exit; } }
		$key = wp_generate_password( 20, false, false );
		$message = Plugin::instance()->notifications->tokens( (string) ( $confirmation['value'] ?? '' ), $form, $values, $entry_id );
		set_transient( 'nyforms_confirmation_' . $key, array( 'form_id' => $form_id, 'message' => $message ), MINUTE_IN_SECONDS * 5 );
		wp_safe_redirect( add_query_arg( array( 'nyforms_submitted' => $form_id, 'nyforms_confirmation' => $key ), wp_get_referer() ?: home_url( '/' ) ) ); exit;
	}
	private function confirmation( $items, $values ) { foreach ( $items as $item ) { if ( Conditions::matches( $item['conditions'], $values ) ) { return $item; } } return array( 'type' => 'message', 'value' => '' ); }
	private function save_resume( $form ) {
		if ( empty( $form['definition']['settings']['save_resume'] ) ) { $this->fail( $form['id'], array( 'form' => __( 'Saving is not enabled for this form.', 'nyforms' ) ) ); }
		$values = array(); foreach ( (array) wp_unslash( $_POST['nyforms_values'] ?? array() ) as $key => $value ) { $values[ sanitize_key( $key ) ] = is_array( $value ) ? array_map( 'sanitize_text_field', $value ) : sanitize_textarea_field( $value ); }
		$key = wp_generate_password( 32, false, false ); set_transient( 'nyforms_resume_' . $key, array( 'form_id' => $form['id'], 'values' => $values ), WEEK_IN_SECONDS );
		$url = add_query_arg( array( 'nyforms_resume' => $key, 'nyforms_saved' => 1 ), wp_get_referer() ?: home_url( '/' ) ); wp_safe_redirect( $url ); exit;
	}
	private function rate_allowed() { $key = 'nyforms_rate_' . md5( wp_privacy_anonymize_ip( $_SERVER['REMOTE_ADDR'] ?? '' ) ); $count = (int) get_transient( $key ); $limit = absint( ( get_option( 'nyforms_settings', array() )['rate_limit'] ?? 10 ) ); if ( $count >= $limit ) { return false; } set_transient( $key, $count + 1, HOUR_IN_SECONDS ); return true; }
	private function recaptcha_valid() { $settings = get_option( 'nyforms_settings', array() ); if ( empty( $settings['recaptcha_enabled'] ) ) { return true; } $secret = sanitize_text_field( $settings['recaptcha_secret_key'] ?? '' ); $token = sanitize_text_field( wp_unslash( $_POST['g-recaptcha-response'] ?? '' ) ); if ( '' === $secret || '' === $token ) { return false; } $response = wp_remote_post( 'https://www.google.com/recaptcha/api/siteverify', array( 'timeout' => 10, 'body' => array( 'secret' => $secret, 'response' => $token, 'remoteip' => wp_privacy_anonymize_ip( $_SERVER['REMOTE_ADDR'] ?? '' ) ) ) ); if ( is_wp_error( $response ) || 200 !== wp_remote_retrieve_response_code( $response ) ) { return false; } $body = json_decode( wp_remote_retrieve_body( $response ), true ); if ( empty( $body['success'] ) ) { return false; } $expected = wp_parse_url( home_url(), PHP_URL_HOST ); $hostname = sanitize_text_field( $body['hostname'] ?? '' ); return ! $hostname || ! $expected || $hostname === $expected || substr( $hostname, -strlen( '.' . $expected ) ) === '.' . $expected; }
	private function store_file( $entry_id, $field_key, $upload ) { require_once ABSPATH . 'wp-admin/includes/file.php'; require_once ABSPATH . 'wp-admin/includes/media.php'; require_once ABSPATH . 'wp-admin/includes/image.php'; $result = wp_handle_sideload( $upload['_upload'], array( 'test_form' => false ) ); if ( ! empty( $result['error'] ) ) { return; } $attachment = wp_insert_attachment( array( 'post_mime_type' => $upload['_mime'], 'post_title' => sanitize_file_name( $upload['_upload']['name'] ), 'post_status' => 'private' ), $result['file'] ); if ( ! is_wp_error( $attachment ) ) { $metadata = wp_generate_attachment_metadata( $attachment, $result['file'] ); wp_update_attachment_metadata( $attachment, $metadata ); Plugin::instance()->repository->attach_file( $entry_id, $field_key, $attachment, $upload['_upload']['name'], $upload['_mime'] ); } }
	private function fail( $form_id, $errors ) { $key = wp_generate_password( 20, false, false ); set_transient( 'nyforms_errors_' . $key, $errors, MINUTE_IN_SECONDS * 5 ); wp_safe_redirect( add_query_arg( 'nyforms_errors', $key, wp_get_referer() ?: home_url( '/' ) ) ); exit; }
}
